- name: Kubernetes on Azure
  href: ./index.yml
- name: 概要
- name: クイックスタート
  expanded: true
- name: チュートリアル
- name: 概念
- name: 操作方法ガイド
  items:
    - name: Azure Files によるデータ保持
      href: ../../aks/azure-files-dynamic-pv.md?toc=/azure/container-service/kubernetes/toc.json
    - name: モニター
    - name: Spring Boot アプリのデプロイ
      items:
        - name: Azure Container Service で Spring Boot アプリケーションを Linux にデプロイする
          href: container-service-deploy-spring-boot-app-on-linux.md
        - name: Azure Container Service で Spring Boot アプリケーションを Kubernetes クラスターにデプロイする
          href: container-service-deploy-spring-boot-app-on-kubernetes.md
        - name: fabric8 Maven プラグインを使用して Spring Boot アプリをデプロイする
          href: container-service-deploy-spring-boot-app-using-fabric8-maven-plugin.md
- name: リファレンス
  items:
    - name: Azure CLI
      href: /cli/azure/acs
    - name: PowerShell
      href: /powershell/module/az.compute
    - name: REST
      href: /rest/api/container-service
- name: リソース
  items:
    - name: Azure のロードマップ
      href: 'https://azure.microsoft.com/roadmap/'
    - name: テンプレート - ACS Engine
      href: 'https://github.com/Azure/acs-engine'
    - name: 価格
      href: 'https://azure.microsoft.com/pricing/details/container-service/'
    - name: 利用可能なリージョン
      href: 'https://azure.microsoft.com/regions/services/'
    - name: Stack Overflow
      href: 'https://stackoverflow.com/questions/tagged/azure-container-service'
    - name: ビデオ
      href: 'https://azure.microsoft.com/resources/videos/index/?services=container-service&sort=newest'